var _ = require('lodash');
var async = require('async');

var mockTimePieces = [
    {date: new Date(), type: "issue", subject: "Worked on xyz", body: "1. Did a burn mode click to dial to a Next Record. it failed cause it’s a n..." },
    {date: new Date(), type: "email", subject: "#7610 grafana - improve the usability of...", body: "Wrote a bunch out and closed the tab before i saved it...Discovered that fl..."}
];

/**
 *
 * @param {User} user the user object to fetch for
 * @param {Object} opts
 * @param {Date} opts.startTime if not specified, defaults to 24 hours from now.
 * @param {Date} [opts.endTime] if not specified, defaults to present time.
 * @param {Function} callback(err, [TimePieces])
 */
exports.fetch = function( user, opts, callback ) {
    return callback(null, mockTimePieces);
};

//
// 0   1/23 02:07pm Mon  issue  #7610 grafana - improve the usability of...  mateus was doing some investigations into crmLayer failures.  I spruced it ...
// 1   1/23 01:20pm Mon  issue  #7584 [salesforce] a16z & exness - getAc...  **Is this a BUG REPORT or FEATURE REQUEST or PROFESSIONAL SERVICES?**:BUG**...
// 2   1/23 01:20pm Mon  issue  #7584 [salesforce] a16z & exness - getAc...  Wrote a bunch out and closed the tab before i saved it...Discovered that fl...
// 3   1/23 12:55pm Mon  issue  #3441 [callmw] Getting wrong contact aft...  1. Did a burn mode click to dial to a Next Record. it failed cause it’s a n...
// 4   1/23 12:33pm Mon  chat   @kane                                        the fuze ones? |
// 5   1/23 12:32pm Mon  chat   @mateus                                      no | but possibly related i feel like sockets are sketchy recently | like f...
// 6   1/23 11:16am Mon  chat   @sean                                        hey brotha | A16Z… flightCheck doesn’t return anything on opportunities | T...
// 7   1/23 11:08am Mon  chat   @sarah                                       hey got the screenshot | i put a bit of work into the RC Recordings this we...
// 8   1/23 11:07am Mon  chat   @bgiven                                      yo | how familiar are you with dealing with salesforce permission oddities ...
// 9   1/23 10:09am Mon  chat   #problems                                    I was having a trouble with the switch functionality on thursday or friday....
//     10  1/23 09:28am Mon  email  Relate to Opportunities                      Gaetan Barthelemy <gaetan@a16z.com>, Mahesh Iyer <mahesh@a16z.com>, Hi Gaet...
//     11  1/23 04:59am Mon  issue  #7601 [rcnative] - call recording links ...  **Is this a BUG REPORT or FEATURE REQUEST or PROFESSIONAL SERVICES?**:Featu...
//     12  1/23 04:59am Mon  issue  #7601 [rcnative] - call recording links ...  I experimented with the RC API this evening.Encountered a few potential iss...
//     13  1/22 10:44pm Sun  chat   @kessiler                                    hey brotha | ```query = _.pick(query, _.identity);``` | i don’t get what th...
//     14  1/22 10:27pm Sun  issue  #7584 [salesforce] a16z & exness - getAc...  Discovered the issue is relateToOpportunity was not enabled in preferences....
//     15  1/22 09:50pm Sun  issue  #5472 lsblk command not found                Started appearing in mine and bernardo's code when we run anything... lsblk...
//     16  1/22 09:43pm Sun  issue  #7278 common._updateCall will call callb...  Stumbled upon this i'm pretty sure this is a bug.Looks like the callback wi...
//     17  1/21 07:31pm Sat  issue  #7419 [lp] - ctdRequest isn't saved          Looks like the LP originate path will not update the ctdRequest objects.![i...
//     18  1/20 04:29pm Fri  issue  #7552 bug/7521-asterisk-pubnub-not-produ...  fixes #7521 **Release note**:```release-noteFixes an issue where certain as...
//    19  1/20 11:11am Fri  issue  #7575 [rcnative] once softphone is check...  **Is this a BUG REPORT or FEATURE REQUEST or PROFESSIONAL SERVICES?**:Bug**...
//    20  1/20 11:07am Fri  issue  #7570 fix path to database helper for 2 ...  **Release note**:```release-noteRepaired two internal tools```Notes To Revi...
//    21  1/20 10:08am Fri  issue  #7461 [CE] Rcnative / CTD parse always u...  Bug, CE CTD for RingCentral always does softphone.  All links have the rcmo...
//    22  1/20 09:51am Fri  issue  #7461 [CE] Rcnative / CTD parse always u...  @pedroassis I just tested it and this change was not pulled into v3.4.168.1...
//    23  1/20 07:37am Fri  email  Re:                                          luis <luis@westerncapitalfunding.com>, Luis, I investigated what caused the...
//    24  1/20 12:53am Fri  issue  #6746 Total Merchant Resources Sporadic ...  ## Internal NotesI generated the report below using tools/ctd-report and an...
//    25  1/19 11:42pm Thu  issue  #7198 [Data] - get counts of sales vs. s...  It would be useful to know what percent of our userbase is sales vs. suppor...
//    26  1/19 11:42pm Thu  issue  #7198 [Data] - get counts of sales vs. s...  closing as it met the immediate needs.